pool:
  vmImage: 'windows-2022'

variables:
- group: 'dotnet-config'
- group: 'github-config'

steps:
- checkout: self
  persistCredentials: true
- task: SSMClientToolsSetup@1
  displayName: 'Setup DigiCert Tools'
  inputs:
    APIKey: '$(SM_API_KEY)'
- task: DownloadSecureFile@1
  displayName: 'Download Client Authentication Certificate'
  name: SM_CLIENT_CERT_FILE
  inputs:
    secureFile: ClientCert.p12
- task: PowerShell@2
  displayName: 'Prepare Code Signing'
  inputs:
    targetType: 'inline'
    script: |
      $env:PATH += ';C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64;C:\Program Files\DigiCert\DigiCert Keylocker Tools'
      $env:SM_LOG_OUTPUT = 'console'
      smctl credentials save $(SM_API_KEY) $(SM_CLIENT_CERT_PASSWORD)
      smksp_cert_sync.exe
    failOnStderr: true
    pwsh: true
- task: PowerShell@2
  displayName: 'Get Version Number'
  inputs:
    filePath: 'azure-gitversion.ps1'
    failOnStderr: true
    pwsh: true
- task: Assembly-Info-NetCore@2
  displayName: 'Apply Assembly Infos'
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: '**/*.csproj'
    InsertAttributes: true
    FileEncoding: 'auto'
    WriteBOM: false
    VersionNumber: '$(MajorVersion).$(MinorVersion).$(PatchVersion).$(Build.BuildId)'
    FileVersionNumber: '$(MajorVersion).$(MinorVersion).$(PatchVersion).$(Build.BuildId)'
    InformationalVersion: '$(SemVersion)'
    LogLevel: 'verbose'
    FailOnWarning: false
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '*.sln'
    feedsToUse: 'select'
    vstsFeed: '340e7a34-33ea-4418-8b72-d55dcb74efa7/dd1a6c3c-4e29-44c2-a80d-9d6c7004ac57'
- task: DotNetCoreCLI@2
  displayName: 'Publish x64'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/SqlDocs.App.csproj'
    arguments: '/p:PublishProfile=x64 /p:Version=$(SemVersion)'
    zipAfterPublish: false
    modifyOutputPath: false
- task: DotNetCoreCLI@2
  displayName: 'Publish x86'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/SqlDocs.App.csproj'
    arguments: '/p:PublishProfile=x86 /p:Version=$(SemVersion)'
    zipAfterPublish: false
    modifyOutputPath: false
- task: DotNetCoreCLI@2
  displayName: 'Publish portable'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/SqlDocs.App.csproj'
    arguments: '/p:PublishProfile=Portable /p:Version=$(SemVersion)'
    zipAfterPublish: false
    modifyOutputPath: false
- task: PowerShell@2
  displayName: 'Sign EXE files'
  inputs:
    targetType: 'inline'
    script: |
      $env:PATH += ';C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64;C:\Program Files\DigiCert\DigiCert Keylocker Tools'
      $env:SM_HOST = '$(SM_HOST)'
      $env:SM_CLIENT_CERT_FILE = '$(SM_CLIENT_CERT_FILE.secureFilePath)'
      $env:SM_LOG_OUTPUT = 'console'
      signtool.exe sign /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /sha1 $(SM_CERT_FINGERPRINT) $(Build.SourcesDirectory)/src/bin/Publish/win-x64/SqlDocs.exe
      signtool.exe sign /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /sha1 $(SM_CERT_FINGERPRINT) $(Build.SourcesDirectory)/src/bin/Publish/win-x86/SqlDocs.exe
      signtool.exe sign /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /sha1 $(SM_CERT_FINGERPRINT) $(Build.SourcesDirectory)/src/bin/Publish/portable/SqlDocs.exe
    failOnStderr: true
    pwsh: true
- task: DotNetCoreCLI@2
  displayName: 'Build MSI Setup x64'
  inputs:
    command: 'build'
    projects: 'setup/SqlDocs.Setup.wixproj'
    arguments: '-c $(BuildConfiguration) -p:Platform=x64 -o $(Build.ArtifactStagingDirectory)'
- task: DotNetCoreCLI@2
  displayName: 'Build MSI Setup x86'
  inputs:
    command: 'build'
    projects: 'setup/SqlDocs.Setup.wixproj'
    arguments: '-c $(BuildConfiguration) -p:Platform=x86 -o $(Build.ArtifactStagingDirectory)'
- task: ArchiveFiles@2
  displayName: 'Create Zip for portable'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/src/bin/Publish/portable/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/sqldocs-portable.zip'
    replaceExistingArchive: true
- task: PowerShell@2
  displayName: 'Sign MSI files'
  inputs:
    targetType: 'inline'
    script: |
      $env:PATH += ';C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64;C:\Program Files\DigiCert\DigiCert Keylocker Tools'
      $env:SM_HOST = '$(SM_HOST)'
      $env:SM_CLIENT_CERT_FILE = '$(SM_CLIENT_CERT_FILE.secureFilePath)'
      $env:SM_LOG_OUTPUT = 'console'
      signtool.exe sign /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /sha1 $(SM_CERT_FINGERPRINT) $(Build.ArtifactStagingDirectory)/sqldocs-x64.msi
      signtool.exe sign /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /sha1 $(SM_CERT_FINGERPRINT) $(Build.ArtifactStagingDirectory)/sqldocs-x86.msi
    failOnStderr: true
    pwsh: true
- task: PowerShell@2
  displayName: 'Push code to GitHub'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    targetType: 'inline'
    script: |
      git remote add github https://$(PAT)@github.com/openpotato/sqldocs.git
      git fetch github
      git checkout .
      git push github HEAD:main
      git push --tags github HEAD:main
    pwsh: true
- task: GitHubRelease@1
  displayName: 'Create GitHub Release'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    gitHubConnection: 'stuebersystems'
    repositoryName: 'openpotato/sqldocs'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    title: '$(SemVersion) Release of SqlDocs'
    addChangeLog: false
